{% set version = "0.7.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyseurat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyseurat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyseurat/tidyseurat_{{ version }}.tar.gz
  sha256: ba3600f067cd5c57ec95ac6ee43912230cc5558097196073f035765ad288df7b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-seurat
    - r-seuratobject
    - r-cli
    - r-dplyr
    - r-ellipsis
    - r-fansi
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-pillar
    - r-plotly
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.2.0
    - r-tidyselect
    - r-ttservice
    - r-vctrs
  run:
    - r-base
    - r-seurat
    - r-seuratobject
    - r-cli
    - r-dplyr
    - r-ellipsis
    - r-fansi
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-pillar
    - r-plotly
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.2.0
    - r-tidyselect
    - r-ttservice
    - r-vctrs

test:
  commands:
    - $R -e "library('tidyseurat')"           # [not win]
    - "\"%R%\" -e \"library('tidyseurat')\""  # [win]

about:
  home: https://stemangiola.github.io/tidyseurat/
  dev_url: https://github.com/stemangiola/tidyseurat
  doc_url: https://stemangiola.github.io/tidyseurat/reference/index.html
  license: GPL-3.0-only
  summary: It creates an invisible layer that allow to see the 'Seurat' object as tibble and interact seamlessly with the tidyverse.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
